blog/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
                                    registrations: 'registrations' }

  get 'welcome/index'

  root 'welcome#index'

  resources :articles do
    resources :comments
  end

  mount Blog::API, at: '/'

  mount GrapeSwaggerRails::Engine => '/swagger'
end

blog/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blog/app/models/article.rb
# Model for articles
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

blog/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

blog/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable, 
         :omniauthable, omniauth_providers: %i[facebook google_oauth2]

  def self.from_omniauth(auth)
    user = User.where(provider: auth.provider, uid: auth.uid).first
    # if oauth_user exists, do nothing
    unless user
      puts 'no existing oauth'
      user = User.find_by(email: auth.info.email)
      # if normal user exists, dont create a new one
      unless user
        puts 'new user'
        user = User.new
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
      end
      user.provider = auth.provider
      user.uid = auth.uid
      user.first_name = auth.info.first_name if user.first_name.blank?
      user.last_name = auth.info.last_name if user.last_name.blank?
      user.display_name = "#{auth.info.first_name} #{auth.info.last_name}" if user.display_name.blank?

      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      user.skip_confirmation!
      user.save
    end
    user
  end

  # Allow accounts to be email-less if using OAuth
  def email_required?
    true unless provider?
  end
end

blog/app/controllers/api/v1/articles.rb
module API
  module V1
    ## Defines article API
    class Articles < Grape::API
      resource :articles do
        desc 'Gets all articles.'
        get do
          Article.all
        end

        desc 'Get specific article.'
        params do
          requires :id
        end
        get :id do
          Article.find(params[:id])
        end
      end
    end
  end
end

blog/app/controllers/api/v1/base.rb
module API
  module V1
    ## Load the v1 API components
    class Base < Grape::API
      version ['v1'], using: :path

      mount API::V1::Articles
    end
  end
end

blog/app/controllers/api/v1/comments.rb
module API
  module V1
    ## Defines comment API
    class Comments < Grape::API
      namespace :articles do
        route_param :article_id do
          resource :comments do
            desc 'Get all comments'
            get do
              Articles.find(param[:article_id]).comments
            end
          end
        end
      end
    end
  end
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def admin_check
    unless current_user.admin?
      flash.alert = 'Requires Admin Access!'
      redirect_to articles_path
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name display_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name display_name])
  end
end

blog/app/controllers/articles_controller.rb
# Defines article api behavior
class ArticlesController < ApplicationController
  before_action :admin_check, only: %i[new create update destroy]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

blog/app/controllers/comments_controller.rb
# Defines comment api behavior
class CommentsController < ApplicationController
  before_action :admin_check, only: %i[destroy]

  def create
    @article = Article.find(params[:article_id])

    @comment = @article.comments.new
    @comment.commenter = current_user.display_name
    @comment.body = comment_params[:body]

    unless @comment.save
      error! @comment.errors, 400
    end

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

blog/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    protected

    def update_resource(resource, params)
            if current_user.provider.nil?
                resourse.update_with_password(params)
            else
                params.delete("current_password")
                resource.update_without_password(params)
            end
    end

end

blog/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication 
      set_flash_message(:notice, :success, kind: "Google") if is_navigational_format?
    else
      session["devise.google_data"] = request.env["omniauth.auth"].except(:extra) # Remove extra to prevent overflow
      redirect_to new_user_registration_url, alert: @users.errors.full_messages.join('\n')
    end
  end

  def failure
    redirect_to root_path
  end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_form.html.erb
<%= form_with model: @article, :html => {:class => "form-horizontal center"}, local: true do |form| %>
    
    <%# Check for errors and display if present %>
    <% if @article.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@article.errors.count, "error") %>
                prohibited this article from being saved:
            </h2>
            <ul>
                <% @article.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <%# Begin Form %>
    <div class="form-group">
        <%= form.label :title, class: "col-md-4 control-label" %><br>
        <%= form.text_field :title, class: "form-control" %>
    </p>

    <p>
        <%= form.label :text %><br>
        <%= form.text_area :text %>
    </p>

    <p>
        <%= form.submit %>
    <p/>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Edit Article<h1/>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Drew's Musings</h1>

<% if current_user.admin? %>
  <%= button_to 'New article', new_article_path,
      method: :get,
      :class => "btn btn-default"%>
<% end %>

<hr>

<table class="table table-hover table-condensed">
    <% @articles.each do |article| %>
      <tr data-href="<%= article_path(article) %>">
        <td><%= article.created_at.strftime "%d %b %y" %></td>
        <td>
          <strong><%= article.title %></strong>
          <p><%= article.text %></p>
        </td>
        <td><%= button_to 'Show', article_path(article),
          method: :get,
          :class => "btn btn-primary" %></td>
        <% if current_user.admin? %>
          <td><%= button_to 'Edit', edit_article_path(article),
                  method: :get,
                  :class => "btn btn-default"%></td>
          <td><%= button_to 'Delete', article_path(article),
                  :class => "btn btn-danger",
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>New Article<h1/>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<h1>
  <%= @article.title %>
</h1>

<p>
  <%= @article.text %>
</p>

<hr>
<h4>Comments</h4>
<%= render @article.comments %>

<hr>
<h4>Add a comment:</h4>
<%= render 'comments/form' %>

<%= link_to 'Edit', edit_article_path(@article), :class => "btn btn-primary" %>
<%= link_to 'Back', articles_path, :class => "btn btn-default" %>

blog/app/views/comments/_comment.html.erb
<strong>
  <%= comment.commenter %>
</strong>

<p>
  <%= comment.body %>
</p>

<% if current_user.admin? %>
  <p>
    <%= button_to  "Delete Comment", [comment.article, comment],
                  method: :delete,
                  data: {confirm: 'Are you sure?' },
                  :class => "btn btn-danger btn-xs" %>
  </p>
<% end %>

blog/app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit 'Create Comment', :class => "btn btn-primary"%>
  </p>
<% end %>

blog/app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

blog/app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

blog/app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

blog/app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Blog" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

blog/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

blog/app/views/welcome/index.html.erb
<h1>Hello, Rails Blog!!<h1/>

<%= link_to 'Drew\'s Blog', controller: 'articles' %> 